// GENERATED by scripts/build-skills-manifest.mjs — do not edit. Sources: ../../skills/*/SKILL.md (agent skills) and ../../app-skills/*/SKILL.md (app-teaching skills)
export interface SkillManifestEntry {
  id: string;
  name: string;
  description: string;
  kind: "workflow" | "capability" | "app";
  files: string[];
  /** App-teaching skills only: bundle identifiers, browser host suffixes, prompt surfaces. */
  apps?: string[];
  sites?: string[];
  surfaces?: string[];
}

export const SKILLS_MANIFEST: SkillManifestEntry[] = [
  {
    "id": "cua-driver",
    "name": "cua-driver",
    "description": "Drive native macOS apps and browser UI through OpenClicky's local computer-use MCP server, backed by Cua Driver. Snapshot AX state, act by element_token with delivery_mode \"background\", keep work backgrounded, prefer the user's default browser, and verify via the action's effect field plus re-snapshot. Use when the user asks you to operate, drive, automate, or perform a GUI task in a real macOS application on the host.",
    "kind": "capability",
    "files": [
      "README.md",
      "RECORDING.md",
      "SKILL.md",
      "TESTS.md",
      "WEB_APPS.md"
    ]
  },
  {
    "id": "doc",
    "name": "doc",
    "description": "Use when the task involves reading, creating, or editing `.docx` documents, especially when formatting or layout fidelity matters; prefer `python-docx` plus the bundled `scripts/render_docx.py` for visual checks.",
    "kind": "capability",
    "files": [
      "SKILL.md",
      "scripts/render_docx.py"
    ]
  },
  {
    "id": "figma",
    "name": "Figma",
    "description": "Teaching notes for Figma — toolbar, layers panel, properties panel, prototyping, exporting, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.figma.Desktop"
    ],
    "sites": [
      "figma.com"
    ],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "finder",
    "name": "Finder",
    "description": "Teaching notes for the macOS Finder — sidebar, toolbar, views, file operations, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.apple.finder"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "frontend-design",
    "name": "frontend-design",
    "description": "Build or improve frontend UI for websites, apps, dashboards, landing pages, and local previews. Use when the user asks for a working interface, visual redesign, UI polish, layout fixes, responsive behavior, or purposeful animation/micro-interactions. Do not use for static documents, Google Workspace tasks, or GUI clicking through an existing app.",
    "kind": "capability",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "github",
    "name": "GitHub",
    "description": "Teaching notes for github.com — repository tabs, code view, pull requests, issues, actions, settings, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [],
    "sites": [
      "github.com"
    ],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "gmail",
    "name": "Gmail",
    "description": "Teaching notes for Gmail in the browser — inbox layout, compose, search operators, labels, filters, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [],
    "sites": [
      "mail.google.com"
    ],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "google-chrome",
    "name": "Google Chrome",
    "description": "Teaching notes for Google Chrome on macOS — omnibox, tabs, extensions, profiles, DevTools, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.google.Chrome"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "google-docs",
    "name": "Google Docs",
    "description": "Teaching notes for Google Docs in the browser — menus, toolbar, outline, comments, sharing, export, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [],
    "sites": [
      "docs.google.com"
    ],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "mail",
    "name": "Mail",
    "description": "Teaching notes for Apple Mail — mailboxes sidebar, message list, viewer, compose window, filters, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.apple.mail"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "notes",
    "name": "Notes",
    "description": "Teaching notes for Apple Notes — folders, notes list, editor toolbar, checklists, tables, sharing, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.apple.Notes"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "obsidian",
    "name": "obsidian",
    "description": "Read, search, create, and edit notes in the configured Obsidian vault.",
    "kind": "capability",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "openclicky-artifacts",
    "name": "openclicky-artifacts",
    "description": "Open, reveal, find, export, rename, move, organize, or explain existing OpenClicky-generated files and local artifacts. Use when the user asks where a PDF, CSV, DOCX, PPTX, XLSX, HTML page, report, deck, video, image, or generated file went, asks to open it again, show it in Finder, export it, or organize it. Do not use for creating the content from scratch unless another workflow already produced the artifact.",
    "kind": "workflow",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "openclicky-build-preview",
    "name": "openclicky-build-preview",
    "description": "Build, modify, launch, preview, and iterate websites, web apps, dashboards, landing pages, HTML files, React/Next apps, and frontend UI. Use when the user wants a visible working thing, not only code.",
    "kind": "workflow",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "openclicky-creative-studio",
    "name": "openclicky-creative-studio",
    "description": "Route broad creative work to available OpenClicky capabilities: frontend polish, design critique, brand/social planning, document/PDF outputs, spreadsheet/table outputs, and existing visual artifact handling. Provider-backed image, video, motion, and new slide/deck generation are not shipped unless the runtime explicitly exposes those capabilities.",
    "kind": "workflow",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "openclicky-dev-setup-doctor",
    "name": "openclicky-dev-setup-doctor",
    "description": "Diagnose and fix developer environment, agent runtime, MCP, API key, package manager, localhost, Node/npm/Python, Supabase, Cloudflare/Wrangler, Codex, Claude Code, and terminal setup problems.",
    "kind": "workflow",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "openclicky-email-assistant",
    "name": "openclicky-email-assistant",
    "description": "Draft, rewrite, summarize, triage, and prepare replies or outreach emails. Use for Gmail/Outlook/Mail tasks, email thread summaries, outbound sequences, follow-ups, humanizing drafts, and Gmail sends that require upgraded send permission plus explicit approval.",
    "kind": "workflow",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "openclicky-google-workspace",
    "name": "openclicky-google-workspace",
    "description": "Use OpenClicky's Composio-backed Google Workspace integration for Gmail read/search, Gmail drafts and approved sends, Calendar events, Drive, Docs, Sheets, unread mail, files in Google Drive, and day-planning tasks.",
    "kind": "workflow",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "openclicky-repo-operator",
    "name": "openclicky-repo-operator",
    "description": "Operate on software repositories and GitHub work: clone/open repos, inspect codebases, explain structure, create branches, commit, push, open PRs, review diffs, respond to review comments, and debug CI or GitHub Actions failures.",
    "kind": "workflow",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "openclicky-research-report",
    "name": "openclicky-research-report",
    "description": "Research a topic, market, competitor set, product, person, or question and turn findings into a useful Markdown, PDF, DOCX, CSV, or brief artifact. Use for competitor research, market intel, source-backed summaries, web research, research briefs, and shareable reports.",
    "kind": "workflow",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "pdf",
    "name": "pdf",
    "description": "Use when tasks involve reading, creating, or reviewing PDF files where rendering and layout matter; prefer visual checks by rendering pages (Poppler) and use Python tools such as `reportlab`, `pdfplumber`, and `pypdf` for generation and extraction.",
    "kind": "capability",
    "files": [
      "SKILL.md"
    ]
  },
  {
    "id": "preview",
    "name": "Preview",
    "description": "Teaching notes for Preview — viewing PDFs and images, the markup toolbar, sidebar thumbnails, annotations, signing, export, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.apple.Preview"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "safari",
    "name": "Safari",
    "description": "Teaching notes for Safari — the toolbar, tabs, sidebar, reader and privacy controls, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.apple.Safari"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "slack",
    "name": "Slack",
    "description": "Teaching notes for Slack — sidebar, channels, message composer, threads, search, huddles, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.tinyspeck.slackmacGap"
    ],
    "sites": [
      "app.slack.com"
    ],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "spreadsheet",
    "name": "spreadsheet",
    "description": "Use when tasks involve creating, editing, analyzing, or formatting spreadsheets (`.xlsx`, `.csv`, `.tsv`) with formula-aware workflows, cached recalculation, and visual review.",
    "kind": "capability",
    "files": [
      "SKILL.md",
      "references/examples/openpyxl/create_basic_spreadsheet.py",
      "references/examples/openpyxl/create_spreadsheet_with_styling.py",
      "references/examples/openpyxl/read_existing_spreadsheet.py",
      "references/examples/openpyxl/styling_spreadsheet.py"
    ]
  },
  {
    "id": "system-settings",
    "name": "System Settings",
    "description": "Teaching notes for macOS System Settings — sidebar sections, search, permissions panes, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.apple.systempreferences"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "terminal",
    "name": "Terminal",
    "description": "Teaching notes for Terminal and iTerm2 — windows, tabs, panes, profiles, shell basics, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.apple.Terminal",
      "com.googlecode.iterm2"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "vercel-deploy",
    "name": "vercel-deploy",
    "description": "Deploy applications and websites to Vercel. Use when the user requests deployment actions like \"deploy my app\", \"deploy and give me the link\", \"push this live\", or \"create a preview deployment\".",
    "kind": "capability",
    "files": [
      "ATTRIBUTION.md",
      "LICENSE.txt",
      "SKILL.md",
      "agents/openai.yaml",
      "assets/vercel-small.svg",
      "assets/vercel.png",
      "scripts/deploy.sh"
    ]
  },
  {
    "id": "vscode",
    "name": "Visual Studio Code",
    "description": "Teaching notes for VS Code — activity bar, sidebar, editor groups, panel, command palette, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.microsoft.VSCode"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "xcode",
    "name": "Xcode",
    "description": "Teaching notes for Xcode — navigator, editor, inspectors, toolbar, running and debugging, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [
      "com.apple.dt.Xcode"
    ],
    "sites": [],
    "surfaces": [
      "talk"
    ]
  },
  {
    "id": "youtube",
    "name": "YouTube",
    "description": "Teaching notes for youtube.com — the header, guide sidebar, player controls, playlists, subscriptions, and what to point at.",
    "kind": "app",
    "files": [
      "SKILL.md"
    ],
    "apps": [],
    "sites": [
      "youtube.com"
    ],
    "surfaces": [
      "talk"
    ]
  }
];
